[package]
name = "feedhandler"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "feedhandler"
path = "src/main.rs"

[dependencies]
shmbus.workspace = true
io-uring.workspace = true
libc.workspace = true
clap.workspace = true
anyhow.workspace = true
ctrlc.workspace = true
serde.workspace = true
serde_json.workspace = true
